### ISSUE TITLE
Error applying behaviour fails fast

### ISSUE THREAD

**Issue by markhobson** [hdpe/jquery-behaviours#1]
If an error occurs when applying a behaviour then any subsequent behaviours are not applied. It'd be nice if jquery-behaviours didn't short-circuit and tried to apply the remaining behaviours.

**Comment by hdpe** [comment]
Hm. Are you proposing doing a `try ... catch` in the behaviour application loop?

If I'm understanding correctly, I'm not sure I like the sound of this. Call me old school, but I'm used to Javascript screw-ups breaking all further JS on the current page. I kind of *like* my broken JS to show itself as a browser console error, spinning up its devtools and breaking on the errant line, with easy local var and stack inspection. And I kind of *like* my broken JS to break the whole page so it's super obvious there's a problem that needs fixing. Your behaviours shouldn't throw errors, so any quiet handling of them just seems to me like it would mask rather than draw attention to problems.

I appreciate it would be annoying if you couldn't see what behaviour was causing your page to break for some reason. But I think what you're describing here is how firing multiple JS snippets with `$(function() {})` or `window.onload = function() {}` or whatever has always behaved.

**Comment by markhobson** [comment]
You're spot on. The old manual jQuery behaviour days were more resilient, e.g. https://jsfiddle.net/08xe71c2/

I don't disagree with you that an error is a bad thing and should be fixed, I just wasn't expecting it to have a knock on effect. My somewhat niche situation was doing a spike on top of a work-in-progress UX mock-up. There was an error that I'd inherited but I was happily ignoring it whilst adding a script. As soon as I moved the script to a behaviour it stopped working. I spent a while checking my behaviour syntax before realising that it was the original error that was stopping it from being applied.

Perhaps some logs to indicate which behaviours were successfully applied, which errored, and any not attempted would have helped. Anyhow, just an idea I thought worth discussing.

**Comment by hdpe** [comment]
Sorry, yes it appears I'm completely wrong - turns out jQuery 3.x introduced some logic to stop  barfing ready handlers affecting other handlers - flick your fiddle's lib version to 2.2.4 to see! And the error still reaches the browser uncaught. I'm not sure what they've done to achieve this.

Logging is always good, but then raises the question of how you configure it. Would you want to turn logging off in production or certain other circumstances?

Anyway, this is an interesting area. Thanks for raising. I'll continue to mull it over. Please do likewise!

Thanks

**Comment by markhobson** [comment]
Good spot, I didn't know that about jQuery 2! From the docs:

> As of jQuery 3.0, jQuery ensures that an exception occuring in one handler does not prevent subsequently added handlers from executing.
-- https://api.jquery.com/ready/

Here's their magic: https://github.com/jquery/jquery/blob/master/src/core/readyException.js

I still like the idea of jquery-behaviour doing its upmost to apply the behaviours in spite of errors. It would align it with the way jQuery works. I agree logging would also be useful, I think just a flag to enable it would suffice.

Thanks for giving it some thought! :+1:
